### ISSUE TITLE
Subsets of the Superset

### ISSUE THREAD

**Issue by melvincarvalho** [w3c/WebID#21]
Once the superset specification has been drafted, we will also need subset specs as outlined in #17 

Which ones should be selected?

Here's my votes:

+1 JSON-LD
+1 Turtle

-1 RDFa
-1 anything that mandates XHTML

+0 everything else

The reasoning behind this is to align with current adoption, popularity with web developers, backwards compatibility, and areas that have a chance of achieving broad adoption and growth.

Happy to hear other opinions on this.

**Comment by jacoscaz** [comment]
> Consider, in HTML you can use RDFa, or a data island in JSON, OR Turtle, it's one too many to be clear with a reasonable default.

@webr3 I like your point! If data islands were to be supported by WebID-Turtle and WebID-JSONLD there would be no need for this group to also specify WebID-RFDa. Agreed.

**Comment by TallTed** [comment]
I am unclear on what is being asked/decided in this issue.

I cannot tell what the "superset specification" is (or is to be).

Nor can I tell what the full list of possible "subset specs" is. Listed here, I see 3 specifics (JSON-LD, Turtle, RDFa) and 2 wildcards ("anything that mandates XHTML", "everything else").

None of this seems to be outlined in #17.

Could someone try to re-write/summarize the question (issue) being discussed here, in (relatively) plain language?

**Comment by jacoscaz** [comment]
Hi @TallTed ! 

Here's a few links that might help to contextualize this:

1. New chair: https://lists.w3.org/Archives/Public/public-webid/2023Nov/0121.html
2. Nathan's superspec/subspec proposal: https://lists.w3.org/Archives/Public/public-webid/2023Jul/0056.html , originating in https://github.com/w3c/WebID/issues/17
3. Super-early superspec draft: https://jacoscaz.com/WebID/superspec/webid.html

Fundamentally, the idea is to produce a minimal WebID "superspec" (I think another word to describe it would be a _framework_ spec) focusing on the underlying concepts and mechanisms of WebIDs while leaving serialization formats (Turtle, JSON-LD, ...) and specific features (TLS, OIDC, ...) up to subspecs.

The end result should, of course, be functionally compatible with the current version of the spec. The intention is not to create something functionally different but, rather, to re-organize the spec so as to overcome the current impasse and finally get to WebID 1.0.

Amongst other triggers, all this was prompted by the Solid WG intention of taking over the WebID spec, given the long wait for WebID 1.0:  https://github.com/solid/solid-wg-charter/issues/39 . I don't mean this in a bad way, I actually think handing everything over to the Solid WG group is a good idea. But, there is tangible consensus around the superspec/subspec approach and it does feel worth a try.

As for how I became chair... I honestly do not know.

**Comment by melvincarvalho** [comment]
Good idea to separate formats (serializations) and features (authentication, signing, encryption, delegated login).  We dont want a big NxM matrix which would be confusing.  Instead two sections, one for serializations, one for features.  The subset specs can standardize the way they want, based on how the system is used.

**Comment by woutermont** [comment]
Just a suggestion, because the language appears to be confusing to a number of people, and I can see why...

Can we stick to the terminology defined in the [W3C Note on Variability in Specifications](https://www.w3.org/TR/spec-variability)?

**Comment by woutermont** [comment]
Also: before diving into which data formats or features to support, let's park that and focus on the core definition(s)?

**Comment by jacoscaz** [comment]
> Can we stick to the terminology defined in the [W3C Note on Variability in Specifications](https://www.w3.org/TR/spec-variability)?

@woutermont very good point and suggestion, I fully agree. In trying to consider how that note can apply to WebID I have come up with the following:

1. the **WebID spec** should be designed for extensibility through an open-ended list of _profiles_
2. each profile should focus on a specific feature (e.g.: WebID-TLS for authentication through client-side certificates)
3. the spec, and not one of its profiles, should regulate how implementors should qualify their implementations in terms of supported serialization formats

What do you think? How would you apply that note to WebID?

> Also: before diving into which data formats or features to support, let's park that and focus on the core definition(s)?

I agree in principle. For the time being I've intentionally opted to prioritize "breadth-first" rather than "depth-first" until the end of today, focusing on opening new fronts rather than closing existing ones. I feel this is more appropriate in light of https://lists.w3.org/Archives/Public/public-webid/2023Nov/0160.html, which triggered a process that should end in a few hours from now.

**Comment by woutermont** [comment]
> * the **WebID spec** should be designed for extensibility through an open-ended list of _profiles_
> * each profile should focus on a specific feature (e.g.: WebID-TLS for authentication through client-side certificates)
> * the spec, and not one of its profiles, should regulate how implementors should qualify their implementations in terms of supported serialization formats

I actually think this is precisely the way to go 👍

**Comment by jacoscaz** [comment]
> >> Can we stick to the terminology defined in the [W3C Note on Variability in Specifications](https://www.w3.org/TR/spec-variability)?
>> 
>> 1. the **WebID spec** should be designed for extensibility through an open-ended list of _profiles_
>> 2. each profile should focus on a specific feature (e.g.: WebID-TLS for authentication through client-side certificates)
>> 3. the spec, and not one of its profiles, should regulate how implementors should qualify their implementations in terms of supported serialization formats
> 
> I actually think this is precisely the way to go 👍

Excellent. Does anyone in the group object to this way forward? I think this question is particularly relevant for @kidehen, @TallTed  and @jonassmedegaard.

**Comment by csarven** [comment]
As mentioned, if clarifying definitions and requirements is what's needed as part of list of product classes that can be interoperable, that can be done so in the current WebID 1.0 ED with minimal work.

If something is unclear or underspecified, it is useful to look at what's originally intended. As I see it, the WebID 1.0 ED in its totality can be categorised to cover: identification, foundation/abstract, protocol, content/data. The amount of requirements that's needed for products to be interoperable is neither too many or complex, so it is fine to keep them together. Anything that needs to extend any notion or requirement, can still do so without having to necessarily take on everything. It is simpler to introduce/clarify information - within the current scope of the specification - instead of taking a far more complicated path with several specs.

**Comment by kidehen** [comment]
> See #17 the entire point is that WebID as it stands does not specify anything other than dereference to a turtle document with a single meaningless triple.

Are you speaking about a WebID or the WebID Specification? Either way, I don't accept your characterization.

BTW -- implementations of the WebID spec already exist, and they are based on the notion of a WebID that names an Agent unambiguously. 

The main issue with the existing spec, which has been discussed in depth over the years, boils down to:

1. Turtle specificity, for WebID-Profile docs
2. Conflation with a specific authentication protocol

**Comment by melvincarvalho** [comment]
It's important to clarify that there is a consensus to divide WebID into two specifications: a superset and a subset. The Chair has confirmed this long-established agreement.

The superset will be highly minimal, akin to an "abstract class", defining the fundamental concept of a WebID as a URI that unambiguously identifies an Agent. The specifics of what constitutes an Agent and the criteria for this will be clearly outlined.

The current Editor's Draft, specific to Turtle, will remain as it has been for the past decade. However, it's tailored to Turtle. Other specifications can be developed to cater to different serialization profiles, accommodating diverse needs and preferences.

The Solid Working Group is welcome to adopt the Turtle WebID spec and enhance it as needed to ensure compliance.

Meanwhile, the WebID Community Group and related projects can freely progress, fostering innovation in the WebID domain with URIs that unambiguously denote an Agent, thereby facilitating out-of-the-box interoperability.

Given the substantial nature of this work, @jacoscaz has generously offered assistance to bring this to completion. It seems prudent to concentrate on this task before embarking on additional work iterms. Once finalized, the superset specification is expected to be sufficiently generic and stable, requiring little to no changes for years to come.

**Comment by kidehen** [comment]
> The current Editor's Draft, specific to Turtle, will remain as it has been for the past decade. However, it's tailored to Turtle. Other specifications can be developed to cater to different serialization profiles, accommodating diverse needs and preferences.

The current spec can be decoupled from Turtle, via a PR.

**Comment by kidehen** [comment]
> Given the substantial nature of this work, @jacoscaz has generously offered assistance to bring this to completion. It seems prudent to concentrate on this task before embarking on additional work iterms. Once finalized, the superset specification is expected to be sufficiently generic and stable, requiring little to no changes for years to come.

That isn't how I understand the work being done here. 
The highest priority was fixing the current spec by decoupling it from Turtle, and a specific Authentication Protocol (i.e., WebID-TLS). 

There is no such thing as a useful superset of the current WebID spec that won't lead to even more confusion. 

All we need is a spec with the following tweaks:

1. Decoupling from Turtle 
2. Decoupling from WebID-TLS, wherever that occurs (overtly or covertly)
3. Accepting properties outside FOAF for Agent and Profile Document association

Regarding point 3, here are some examples in the wild that already exist i.e., reiterating the utility of Schema.org terms. 

1. https://www2.deloitte.com/us/en/profiles/beena-ammanath.html
2. https://www2.deloitte.com/us/en/profiles/nitin-mittal.html

Note: 
Those profile docs aren't perfect, but they indicate what's happening on the back of Schema.org terms with regards to WebIDs and associated Profile Documents.

This train has long left the station, so it would be wise to get on board by leveraging the "Wisdom of Solomon" principle that I've mentioned repeatedly.

**Comment by kidehen** [comment]
> If you disagree, please prove your point using the specification text to factually find the flaw on #17 - perhaps I missed a MUST when reviewing.

That isn't how the point is proven, since I don't agree with your characterization neither here nor in issue 17.

You assert:
> I can't see any specification, would be my overriding point here, all that the spec actually specifies in any implementable way, is that an HTTP URI is a WebID Profile if it dereferences to literally any text/turtle response.

My position:
You are simply highlighting what needs to be fixed i.e., making the WebID Specification about the user of an HTTP URI for naming Entities Unambiguously.  The WebID-Profile document to which a WebID resolves is a different matter. 

What's the conformance test? 
Naming an entity unambiguously using an HTTP URI. 

Examples that pass that basic test:

1. https://www2.deloitte.com/us/en/profiles/nitin-mittal.html#person
2. https://www2.deloitte.com/us/en/profiles/beena-ammanath.html/#person

The issue of profile document content-type only arises when implementing an Authentication Protocol, which is a totally different spec.

**Comment by melvincarvalho** [comment]
> > The Solid Working Group is welcome to adopt the Turtle WebID spec and enhance it as needed to ensure compliance.
> 
> I have no sense of any group seeking to adopt a Turtle-specific WebID spec. Where is this presumption coming from?

https://lists.w3.org/Archives/Public/public-webid/2023Jul/0065.html

**Comment by kidehen** [comment]
> Every HTTP URI passes that test. So what distinguishes one as a WebID, or better as naming an tbd:Agent.

The fact that it is used to denote an agent (person or organization) in a recognizable way, as per my examples. This includes human eyeballs and/or software applications i.e., not just software application which introduce content processing -- naturally. 

The moment content-processing enters the mix, we enter the Profile Document realm en route to Authentication Protocol implementation -- since said protocol is all about Identity Authenticity. 

Above all else, the grounding principles I espouse repeatedly regarding this matter boil down to loose-coupling of the following:

1. Identity -- an identifier offers that e.g., a WebID (which is about using an HTTP URI in this regard)
2. Identification -- a Profile Doc offers that
3. Authentication -- an authentication protocol offers that
4. Authorization -- attribute-based access controls (via ontology and processors) offer that
5. Storage -- various protocols handle that

**Comment by kidehen** [comment]
> I presume I'm missing something here and your not suggesting that if uri contains the string person then it's a webid.

I am not saying "person" has any bearing on the example HTTP URIs I presented. I am simply saying:
Here are examples of HTTP URIs used to unambiguously name agents. 

An HTTP URI can be constructed from an HTTP URL by simply tacking on a "#" indexical. That's what I am referring to, specifically. 

The WebID spec is supposed to be about how you construct a name from a specific kind of identifier.

**Comment by jonassmedegaard** [comment]
I agree with @webr3 here: Scope of WebID spec is to specify what a web agent identifier **is**, and should specify that without expanding into stuff that is potentially ambiguous.

There are potentially multiple ways to resolve a name of an agent from an identifier of same agent, so such specification does **not** belong in the WebID spec. Possibly there could be multiple "wns" (WebID Name Resolving) specs, but personally I see no need for that: All the authentication specs proposed so far involve semantic graph extraction, which allows reasoning for various preferences in naming - e.g. "give me the SVG representation of the agent, or a PNG, or a textual representation - and pick the danish variant, or the norwegian, or the british english, or the irish, or if only an american english variant exists then don't resolve to that but instead show the raw IRI".

**Comment by kidehen** [comment]
> I agree with @webr3 here: Scope of WebID spec is to specify what a web agent identifier **is**, and should specify that without expanding into stuff that is potentially ambiguous.

That can be done in prose. Machine-computability of what's expressed in prose is something for a different spec i.e., a profile document or authentication protocol spec. 

```
curl -I https://www2.deloitte.com/us/en/profiles/beena-ammanath.html#this
HTTP/1.1 200 OK
x-dispatcher: aemcloudservice
x-vhost: aemcloudservice
Last-Modified: Wed, 03 Jan 2024 17:31:35 GMT
```

Tells us that `https://www2.deloitte.com/us/en/profiles/beena-ammanath.html` is an unambiguous content address. Thus, it also implies that `https://www2.deloitte.com/us/en/profiles/beena-ammanath.html#this` is an unambiguous name derived from said address. 

A WebID is simply an application of the above, but applied to naming agents (i.e., people, bots, or organizations) rather than anything.

Another possible route out of the current quagmire:

Change the "WebID Identity and Discovery Spec" title to "WebID Profile Document Spec" comprising Turtle and JSON-LD sub-specifications. As part of this approach, a WebID would be described as an HTTP URI for unambiguous entity naming that resolves to documents comprising _content types_ and _entity relationship types_ described in the relevant sub-specifications.

What's outlined above is closer to what I believe @webr3 seeks.

**Comment by kidehen** [comment]
> From my perspective the WebID spec is supposed to allow an implementer to be able to write a simple line of code like: `if(X a Agent) then`.

Yes, this is indeed where we differ. 
From my vantage point, a specification titled "WebID Specification" wouldn't be about what you describe. A specification titled "WebID Profile Document Specification" is a much closer match. 

Right now, we are stuck with "WebID Identity and Discovery Specification" which, as I've [mentioned earlier](https://github.com/w3c/WebID/issues/21#issuecomment-1875997800), is a too-clever attempt at conflating critical items that should be loosely-coupled. The checkered history of this spec is ample proof of my point.

**Comment by melvincarvalho** [comment]
> Without the is a Agent bit, it's not a WebID

Agree on this part.  I think the path forward is to first find a natural language definition, and then take it from there.

**Comment by melvincarvalho** [comment]
> From my vantage point, a specification titled "WebID Specification" wouldn't be about what you describe.

Open to renaming the specs, which will have to be done anyway.  Perhaps we could separate that out into two distinct, but related issues, to avoid talking across each other, or overloading the chair with information in a short burst.

**Comment by kidehen** [comment]
> Rather I'm looking for an HTTP URI as a Name for an Agent spec, a WebID.

As I've tried to explain, using the DBpedia example, this quest always ends up in the same place. There's a boatload of history regarding this matter that dates back to the dreaded HttpRange14 debates, and others that crept into Linked Data Principles. The core matter is the same: attempting to spec an HTTP URI as an unambiguous name for anything (agent or whatever) ends up in the same place. 

Antidote? 
Specify the nature of _the document_ to which an _HTTP URI resolves_, doing so in line with its usage purpose. That way you end up with a usage-specific definition of both an HTTP URI, the Content-Type of the document to which it resolves, and the Entity Relationship Type Semantics represented in the content.

**Comment by melvincarvalho** [comment]
> Antidote?  Specify the nature of the document to which an HTTP URI resolves, doing so in line with its usage purpose. That way you end up with a usage-specific definition of both an HTTP URI, the Content-Type of the document to which it resolves, and the Entity Relationship Type Semantics represented in the content.

On this, it seems a radical departure from the decade long understanding that a WebID is a URI that denotes an Agent.  Perhaps you can come up with an alternative definition and propose it to the group and see if it catches on.

In any case, this thread was opened as a straw poll, and I believe it has achieved its purpose and created a few more items which can be followed elsewhere.  I think we have a rough feel for the shape of extension profiles in turtle and json-ld, with more allowed, which can be ironed out in future.

**Comment by melvincarvalho** [comment]
Closing this issue as it having achieved it's purpose of straw polling and garnering opinion.  Can be reopened if desired.

**Comment by jonassmedegaard** [comment]
> [separately specifying identifier, profile and authentication which *together* specifies a valid authentic agent] seems a radical departure from the decade long understanding that a WebID is a URI that denotes an Agent.

I fail to see how it is a radical depature to separately specifying identifier and profile which *together* specifies a valid agent, given that those have till now only been explored as a single specification.

If you meant something else by "it" (which I replaced in my quote above), then it would be helpful if you elaborate, and I apologise for misinterpreting you.
