### ISSUE TITLE
Open GitHub Discussions

### ISSUE THREAD

**Issue by woutermont** [w3c/WebID#36]
@jacoscaz, could you perhaps open the Discussions functionality of this repo? That would allow us to keep less formal discussions restricted to there.

Just crossed my mind when posting https://github.com/w3c/WebID/issues/35

**Comment by jacoscaz** [comment]
@woutermont I actually do not have administrative access to the repo, yet. As soon as that's settled, this seems like a good idea. Less formal discussions are often carried out on the list but moving everything onto a single platform would be nice.

**Comment by jacoscaz** [comment]
I now have administrative access to this repo. I'll give it a few days and, if nobody objects to this, I'll enable Discussions.

**Comment by melvincarvalho** [comment]
> I now have administrative access to this repo.

Awesome.  Who else has admin access?

In particular who can create a new branch.  It might to start creating branches for new items getting closer to merge.

**Comment by jacoscaz** [comment]
Done, closing this one. 

> Awesome. Who else has admin access?

I think this would ultimately depend on some kind of process we should agree on. I'm still reading through a bunch of material, more soon...

**Comment by melvincarvalho** [comment]
> I think this would ultimately depend on some kind of process we should agree on.

I mean who has access to merge a branch currently.

https://github.com/w3c/WebID/branches

I've observed that branch merges are sometimes being conducted unilaterally by a select few, leading to a noticeable imbalance.

This situation, where only certain individuals have the access and authority to perform these branch merges, is concerning to me. It feels akin to a power grab, and I think it's important for us to apply group fairness.

I have reservations about using Microsoft GitHub as our definitive platform for work, particularly in terms of expanding our footprint there.

**Comment by melvincarvalho** [comment]
FWIW I've always been against working exclusively in w3c/webid for the reason above. It's much better to have our own github org. Which can have multiple repos, e.g. one for specs and one for vocabs. This is what many successful groups do.

So expanding github discussions here, I think is a bad idea. Sorry @woutermont I like the idea in principle. But if we had our own org, our own repos, then discussions, I have no issue with. As someone said we can still use the mailing list, for now.

**Comment by jacoscaz** [comment]
> I mean who has access to merge a branch currently

@melvincarvalho this is likely better discussed elsewhere, in a dedicated issue / discussion / email thread. To answer your question, though, right now @csarven and I have direct administrative access to the repo while many more can access it via their base role in the W3C org (2802 people). I am unsure as to what _access_ means in their case. Perhaps @TallTed can shine some light here so that we can understand what the situation is and how to move forward.

**Comment by TallTed** [comment]
> [@jacoscaz] Perhaps @TallTed can shine some light here so that we can understand what the situation is and how to move forward.

I confess, I'm having trouble following what @melvincarvalho has said above, such as --
>> [@melvincarvalho] access to merge a branch currently. (ie to create a new branch in this repo)

and
>> [@melvincarvalho] In particular who can create a new branch. It might be an idea to start creating branches for new items getting closer to merge.

Generally speaking, a repository has some CODEOWNERS who have full permissions on the content managed within that repo. In the W3 context, these tend to be the Chairs of Working Groups and Community Groups, as well as the Editors of any documents managed by those Groups. Other Group members (as well as all other GitHub users) are able to create Issues and Pull Requests (associated with a specific Branch in a Fork owned by the creator of the PR), which are then addressed by the Group as a whole, and upon consensus on a Pull Request, an Editor or Chair merges that PR into the (usually) `main` branch of the original repository.

The power to merge a PR into the original repository is not globally open, because this is a sure path to boundless spam and other vandalism.

I don't see any point to "creating branches [in this repo] for new items getting closer to merge". Raising a PR inherently involves creating a user-owned branch (in a user-owned fork), which is what is used to generate and present the `https://github.com/w3c/WebID/pulls/.../files` pages associated with each PR. Each such PR should evolve, through suggested changes and other discussion, to a point that the (Working or Community) Group's consensus is that it should be merged (or closed without merging) into the `main` branch for the Group-owned repo.

----

I am generally against the use of GitHub "Discussions", because they really aren't the threaded discussions they originally promised; they're Q&A areas modeled after StackOverflow (and the like). One Question, multiple Answers, with multiple Comments on those Answers -- but no threaded Comments on Comments.

This usually leads to confusion and misunderstanding, as users do not have an easy path to "all Comments since the last time I viewed this Question," as the simplest example, nor to "all Comments on this Comment," nor to "all Comments answering my Comments on this Question," nor to "all Comments answering my Comments on this Answer"....

Someday, enough people with appropriate resources will recognize that [NNTP](https://dbpedia.org/resource/Network_News_Transfer_Protocol) and the infinitely threadable conversations of [USENET](http://dbpedia.org/resource/Usenet) still have significant value outside of the Google Groups silo that was jumpstarted by loading all USENET history they could grab and which will [soon drop its outbound connections to USENET](https://www.pcmag.com/news/end-of-an-era-google-groups-to-drop-usenet-support), and USENET will be well and truly [revived](https://www.theregister.com/2023/08/30/usenet_revival/).
