### ISSUE TITLE
Editors Draft

### ISSUE THREAD

**Issue by webr3** [w3c/WebID#41]
https://www.w3.org/2005/Incubator/webid/spec/drafts/ED-webid-20111212/

> Publication as an Editor's Draft does not imply endorsement by the W3C Membership. **This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.**

https://www.w3.org/2005/Incubator/webid/spec/identity/

> This document is produced from work by the [W3C WebID Community Group](http://www.w3.org/community/webid/). **This is an internal draft document and may not even end up being officially published. It may also be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.**

I believe issues of B.C., compatibility with "WebID 1.0" or any such conversations have no weight, and should be completely disregarded as nothing but an informal nicety.

WebID is **not** a specification.

**Comment by woutermont** [comment]
Replying to above and https://github.com/w3c/WebID/pull/45#issuecomment-1894106265.

> > [@woutermont:] Let's clarify something that seems to be causing some serious confusion: the draft of 2014 is the draft of 2014; we cannot go back in time and change that draft.
> 
> [@webr3] Can you confirm if [#45] is just a have a go type thing that stays as an open issue. Or do you aim to fold this in to main and start making adjustments based on issues you've mentioned here, whilst side-lining the main work of the group in to a WIP/proposal branch?

When I say "the draft of 2014 is the draft of 2014", I mean the documents residing in `https://github.com/w3c/WebID/tree/main/spec/drafts/ED-webid-20140305/`, and published under `https://www.w3.org/2005/Incubator/webid/spec/drafts/ED-webid-20140305/`. That is the latest immutable, versioned draft specification, which current implementations have been targetting since it's publication.

The working documents directly under https://github.com/w3c/WebID/tree/main/spec, however, are the results of the iterations on decisions by the CG since then. When we decide we reached a new draft worth versioning separately, we take a snapshot and move it to `https://github.com/w3c/WebID/tree/main/spec/drafts/2024mmdd/`

As you can see in my Bikeshed PR #45 the [version of the rendered HTML](https://github.com/w3c/WebID/blob/1e3bbf8ba66e5e99f9819087f8bae4360601fc9a/spec/identity/index.html#L465) is set to the date the file is rendered, not to 2014-03-05.

**Comment by jacoscaz** [comment]
_/chair hat on_

I guess merging #45 will effectively resolve this issue. I'll link that PR to this issue.
